swagger: '2.0'
info:
  description: 'Simple API to manage contacts'
  version: '1.0.0'
  title: 'Contacts API'
host: 'localhost:5000'
basePath: '/'
consumes:
  - 'application/json'
produces:
  - 'application/json'
tags:
  - name: 'contact'
    description: 'operations on contacts'
paths:
  /contacts:
    get:
      tags:
        - 'contact'
      summary: 'Get a list of contacts'
      description: ''
      parameters:
        - in: 'query'
          name: 'limit'
          description: 'The number of items per page'
          type: 'string'
          default: '10'
        - in: 'query'
          name: 'offset'
          description: 'The number of items that should be skipped, typically offset = "number of items per page" * ("current page number" - 1)'
          type: 'string'
          default: '0'
        - in: 'query'
          name: 'first_name[equals]'
          description: "first name equality filter"
          type: 'string'
        - in: 'query'
          name: 'first_name[contains]'
          description: "first name contains filter"
          type: 'string'
        - in: 'query'
          name: 'last_name[equals]'
          description: "last name equality filter"
          type: 'string'
        - in: 'query'
          name: 'last_name[contains]'
          description: "last name contains filter"
          type: 'string'
        - in: 'query'
          name: 'sort_by'
          description: "field to sort items by (add .desc suffix to reverse the order and separate fields by a comma for multi-field ordering)"
          type: 'string'
          default: 'last_name.desc,first_name.asc'
          
      responses:
        '200':
          description: 'Everything went well'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/ContactSimplified'
    post:
      tags:
        - 'contact'
      summary: 'Add a new contact'
      description: ''
      parameters:
        - in: 'body'
          name: 'contact'
          description: 'Contact object that needs to be added in DB'
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ContactEditableAttributes'
              - type: 'object'
                required:
                  - 'email'
      responses:
        '201':
          description: 'Created'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'

        '400':
          description: 'Invalid input. The contact object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The contact object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"

  /contacts/{contactId}:
    get:
      tags:
        - 'contact'
      summary: 'Find a contact by ID'
      description: 'Returns a single contact'
      parameters:
        - name: 'contactId'
          in: 'path'
          description: 'ID of contact to return'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'

        '404':
          description: 'contact not found'
    put:
      tags:
        - 'contact'
      summary: 'Update an existing contact'
      description: ''
      parameters:
        - name: 'contactId'
          in: 'path'
          description: 'ID of contact to return'
          required: true
          type: 'integer'
          format: 'int64'
        - in: 'body'
          name: 'contact'
          description: 'contact object that needs to be updated'
          required: true
          schema:
            $ref: '#/definitions/ContactEditableAttributes'
      responses:
        '200':
          description: 'Updated'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Contact not found'
        '400':
          description: 'Invalid input. The contact object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The contact object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"
    delete:
      tags:
        - 'contact'
      summary: 'Deletes a contact'
      description: ''
      parameters:
        - name: 'contactId'
          in: 'path'
          description: 'contact id to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '204':
          description: 'Contact Deleted'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Contact not found'
definitions:
  ValidationError:
    type: 'object'
    properties: 
      errorsByField: 
        type: 'array'
        items: 
          type: 'object'
          properties: 
            type:
              type: "string"
            path:
              type: 'array'
              items: 
                type: 'string'
            message:
              type: 'string'
      errorMessage:
        type: 'string'
  ContactEditableAttributes:
    type: 'object'
    properties:
      first_name:
        type: 'string'
        example: 'John'
      last_name:
        type: 'string'
        example: 'Doe'
      email:
        type: 'string'
        example: 'john.doe@gmail.com'

  ContactSimplified:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
        example: 'John'
      email:
        type: 'string'
        example: 'john.doe@gmail.com'

  Contact:
    allOf:
      - type: 'object'
        properties:
          id:
            type: 'integer'
            format: 'int64'
      - $ref: '#/definitions/ContactEditableAttributes'
