swagger: '2.0'
info:
  description: 'Simple API to manage contacts'
  version: '1.0.0'
  title: 'Contacts API'
host: 'localhost:5000'
basePath: '/'
consumes:
  - 'application/json'
produces:
  - 'application/json'
tags:
  - name: 'contact'
    description: 'operations on contacts'
paths:
  /contacts:
    get:
      tags:
        - 'contact'
      summary: 'Get a list of contacts'
      description: ''
      responses:
        '200':
          description: 'Everything went well'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/ContactSimplified'
    post:
      tags:
        - 'contact'
      summary: 'Add a new contact'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - in: 'body'
          name: 'contact'
          description: 'Contact object that needs to be added in DB'
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ContactEditableAttributes'
              - type: 'object'
                required:
                  - 'email'
      responses:
        '201':
          description: 'Created'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'

        '400':
          description: 'Invalid input. The contact object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The contact object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"
        '401':
          description: 'Unauthorized'

  /contacts/{contactId}:
    get:
      tags:
        - 'contact'
      summary: 'Find a contact by ID'
      description: 'Returns a single contact'
      parameters:
        - name: 'contactId'
          in: 'path'
          description: 'ID of contact to return'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'

        '404':
          description: 'contact not found'
    put:
      tags:
        - 'contact'
      summary: 'Update an existing contact'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - name: 'contactId'
          in: 'path'
          description: 'ID of contact to return'
          required: true
          type: 'integer'
          format: 'int64'
        - in: 'body'
          name: 'contact'
          description: 'contact object that needs to be updated'
          required: true
          schema:
            $ref: '#/definitions/ContactEditableAttributes'
      responses:
        '200':
          description: 'Updated'
          schema:
            type: 'object'
            $ref: '#/definitions/Contact'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Contact not found'
        '400':
          description: 'Invalid input. The contact object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The contact object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"
    delete:
      tags:
        - 'contact'
      summary: 'Deletes a contact'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - name: 'contactId'
          in: 'path'
          description: 'contact id to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '204':
          description: 'Contact Deleted'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Contact not found'

  /users:
    get:
      tags:
        - 'user'
      summary: 'Get a list of users'
      description: ''
      responses:
        '200':
          description: 'Everything went well'
          schema:
            type: 'array'
            items:
              $ref: '#/definitions/UserSimplified'
    post:
      tags:
        - 'user'
      summary: 'Add a new user'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - in: 'body'
          name: 'user'
          description: 'User object that needs to be added in DB'
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/UserEditableAttributes'
              - type: 'object'
                required:
                  - 'email'
      responses:
        '201':
          description: 'Created'
          schema:
            type: 'object'
            $ref: '#/definitions/User'

        '400':
          description: 'Invalid input. The user object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The user object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"
        '401':
          description: 'Unauthorized'

  /users/{userId}:
    get:
      tags:
        - 'user'
      summary: 'Find a user by ID'
      description: 'Returns a single user'
      parameters:
        - name: 'userId'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '200':
          description: 'successful operation'
          schema:
            type: 'object'
            $ref: '#/definitions/User'

        '404':
          description: 'user not found'
    put:
      tags:
        - 'user'
      summary: 'Update an existing user'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - name: 'userId'
          in: 'path'
          description: 'ID of user to return'
          required: true
          type: 'integer'
          format: 'int64'
        - in: 'body'
          name: 'user'
          description: 'user object that needs to be updated'
          required: true
          schema:
            $ref: '#/definitions/UserEditableAttributes'
      responses:
        '200':
          description: 'Updated'
          schema:
            type: 'object'
            $ref: '#/definitions/User'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'User not found'
        '400':
          description: 'Invalid input. The user object was not provided'
          schema:
            type: 'object'
            properties:
              errorMessage:
                type: 'string'
        '422':
          description: 'Invalid input. The user object provided is not valid'
          schema:
            type: 'object'
            $ref: "#/definitions/ValidationError"
    delete:
      tags:
        - 'user'
      summary: 'Deletes a user'
      description: ''
      parameters:
        - name: 'apiKey'
          in: 'query'
          description: 'The key needed to access some parts of the API'
          required: true
          type: 'string'
        - name: 'userId'
          in: 'path'
          description: 'user id to delete'
          required: true
          type: 'integer'
          format: 'int64'
      responses:
        '204':
          description: 'User Deleted'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'User not found'
definitions:
  ValidationError:
    type: 'object'
    properties: 
      errorsByField: 
        type: 'array'
        items: 
          type: 'object'
          properties: 
            type:
              type: "string"
            path:
              type: 'array'
              items: 
                type: 'string'
            message:
              type: 'string'
      errorMessage:
        type: 'string'
  ContactEditableAttributes:
    type: 'object'
    properties:
      first_name:
        type: 'string'
        example: 'John'
      last_name:
        type: 'string'
        example: 'Doe'
      email:
        type: 'string'
        example: 'john.doe@gmail.com'
  UserEditableAttributes:
    type: 'object'
    properties:
      email:
        type: 'string'
        example: 'john.doe@gmail.com'
      password:
        type: 'string'
        example: '2TYVTYUF11@@%yuftrdesszejhvgez'
      password_confirmation:
        type: 'string'
        example: '2TYVTYUF11@@%yuftrdesszejhvgez'

  ContactSimplified:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      name:
        type: 'string'
        example: 'John'
      email:
        type: 'string'
        example: 'john.doe@gmail.com'

  UserSimplified:
    type: 'object'
    properties:
      id:
        type: 'integer'
        format: 'int64'
      email:
        type: 'string'
        example: 'john.doe@gmail.com'

  Contact:
    allOf:
      - type: 'object'
        properties:
          id:
            type: 'integer'
            format: 'int64'
      - $ref: '#/definitions/ContactEditableAttributes'
  User:
    allOf:
      - type: 'object'
        properties:
          id:
            type: 'integer'
            format: 'int64'
      - $ref: '#/definitions/UserEditableAttributes'
